// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1hCqv4f83OcuDYrwRGp-VPxKzGrlyVYQ',
    appId: '1:1037460954730:web:0933956fef7e42c018f413',
    messagingSenderId: '1037460954730',
    projectId: 'pehchankidukan-24b1a',
    authDomain: 'pehchankidukan-24b1a.firebaseapp.com',
    storageBucket: 'pehchankidukan-24b1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANm-dRxTQgTInc1QFqBNvmlhkH3iQuNw4',
    appId: '1:1037460954730:android:87fbedbeb336659418f413',
    messagingSenderId: '1037460954730',
    projectId: 'pehchankidukan-24b1a',
    storageBucket: 'pehchankidukan-24b1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoxHhZG43o8cT3iyL4eAZZzpLOBOYn_lA',
    appId: '1:1037460954730:ios:6af4c65404c8a13518f413',
    messagingSenderId: '1037460954730',
    projectId: 'pehchankidukan-24b1a',
    storageBucket: 'pehchankidukan-24b1a.appspot.com',
    iosBundleId: 'com.rays.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoxHhZG43o8cT3iyL4eAZZzpLOBOYn_lA',
    appId: '1:1037460954730:ios:342ee4766e57c5b218f413',
    messagingSenderId: '1037460954730',
    projectId: 'pehchankidukan-24b1a',
    storageBucket: 'pehchankidukan-24b1a.appspot.com',
    iosBundleId: 'com.rays.eCommerce.RunnerTests',
  );
}
